### ISSUE TITLE
Does not work with gate

### ISSUE THREAD

**Issue by kubo6472** [minekube/connect-demo#1]
```json
{"error": "error handshaking with websocket server: failed to WebSocket dial: failed to send handshake request: Get \"https://watch.connect.api.minekube.com\": dial tcp: lookup watch.connect.api.minekube.com on 127.0.0.11:53: no such host", "retryAfter": "5s"}
```
No idea what's wrong, just enabled
```yml
connect:
  enabled: true
```
I assume the hardcoded domain is dead.
![image](https://user-images.githubusercontent.com/26146502/193904822-77de480d-cc3a-415a-8a09-798643ad5ed4.png)
Please take a look and let me know how can I fix my setup. Thanks.
P.S. If this issue is in the wrong repo, I'm sorry in advance. I have absolutely no idea where does it belong. Please be so kind and move it yourselves. Thank you very much.

**Comment by robinbraemer** [comment]
[Connect](https://connect.minekube.com/) is now live, try updating [Gate](https://gate.minekube.com/) to the latest version!
If you need help feel free to join the [Discord](https://minekube.com/discord) or use GitHub Issues.
Thank your for testing the demo and see you on live!
